services:
  mongo:
    image: mongo:6
    container_name: songs_mongo_db
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
